Repository ssg-java3-240304/PetTopia, pull requests merged in 2024-08, with the labels that each got.

#140 업체 상세보기 페이지 #86
  build.gradle
  src/main/java/com/sh/pettopia/enterprise/controller/EnterpriseController.java
  src/main/resources/static/css/enterprise/detail.css
  src/main/resources/static/js/enterprise/detail.js
  src/main/resources/templates/enterprise/detail.html
  src/main/resources/templates/enterprise/location.html
  src/main/resources/templates/layout/default.html
  src/main/resources/templates/ncpFileUpload/list.html
  src/main/resources/templates/ncpFileUpload/upload.html
Labels: 업체

#146 update : 펫시터는 일 시작 등록을 할 수 있습니다. #70 #47
  .github/workflows/docker-image.yml
  sql/tbl_member.sql
  sql/tbl_petsitter.sql
  src/main/java/com/sh/pettopia/choipetsitter/controller/PetSitterController.java
  src/main/java/com/sh/pettopia/choipetsitter/dto/PetSitterListDto.java
  src/main/java/com/sh/pettopia/choipetsitter/dto/PetSitterRegisterDto.java
  src/main/java/com/sh/pettopia/choipetsitter/entity/AvailableService.java
  src/main/java/com/sh/pettopia/choipetsitter/entity/PetSitter.java
  src/main/java/com/sh/pettopia/ncpTest/FileService.java
  src/main/resources/static/images/availablePetSize/largepet.PNG
  src/main/resources/static/images/availablePetSize/middlepet.PNG
  src/main/resources/static/images/availablePetSize/smallpet.PNG
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/petsitter/calendar_multiple-select.html
  src/main/resources/templates/petsitter/detail.html
  src/main/resources/templates/petsitter/list.html
  src/main/resources/templates/petsitter/registerpost.html
  src/main/resources/templates/petsitter/registerprofile.html
  src/main/resources/templates/petsitter/startjob.html
  src/test/java/com/sh/pettopia/choipetsitter/entity/AvailablePetSize.java
  src/test/java/com/sh/pettopia/choipetsitter/entity/AvailableService.java
  src/test/java/com/sh/pettopia/choipetsitter/entity/PetSitter.java
  src/test/resources/META-INF/persistence.xml
Labels: 펫시터

#173 Feat: [업체] 리뷰 등록 #91
  sql/tbl_ent_review.sql
  sql/tbl_member.sql
  src/main/java/com/sh/pettopia/Hojji/common/paging/PageCriteria.java
  src/main/java/com/sh/pettopia/Hojji/community/posts/controller/CommunityController.java
  src/main/java/com/sh/pettopia/Hojji/community/posts/dto/PostListResponseDto.java
  src/main/java/com/sh/pettopia/Hojji/community/posts/entity/Category.java
  src/main/java/com/sh/pettopia/Hojji/community/posts/entity/Comment.java
  src/main/java/com/sh/pettopia/Hojji/config/CustomAuthenticationSuccessHandler.java
  src/main/java/com/sh/pettopia/Hojji/pet/controller/PetController.java
  src/main/java/com/sh/pettopia/Hojji/pet/entity/ParasitePrevention.java
  src/main/java/com/sh/pettopia/Hojji/pet/repository/PetRepository.java
  src/main/java/com/sh/pettopia/Hojji/pet/service/PetService.java
  src/main/java/com/sh/pettopia/Hojji/user/User.java
  src/main/java/com/sh/pettopia/Hojji/user/member/controller/MemberController.java
  src/main/java/com/sh/pettopia/Hojji/user/member/dto/MemberRegistRequestDto.java
  src/main/java/com/sh/pettopia/Hojji/user/member/service/MemberService.java
  src/main/java/com/sh/pettopia/PetTopiaApplication.java
  src/main/java/com/sh/pettopia/enterprise/controller/HospitalController.java
  src/main/java/com/sh/pettopia/enterprise/controller/PharmacyController.java
  src/main/java/com/sh/pettopia/enterprise/controller/SalonController.java
  src/main/java/com/sh/pettopia/enterprise/dto/ReviewRegistDto.java
  src/main/java/com/sh/pettopia/enterprise/dto/ReviewResponseDto.java
  src/main/java/com/sh/pettopia/enterprise/entity/Rating.java
  src/main/java/com/sh/pettopia/enterprise/entity/Review.java
  src/main/java/com/sh/pettopia/enterprise/repository/ReviewRepository.java
  src/main/java/com/sh/pettopia/enterprise/service/ReviewService.java
  src/main/java/com/sh/pettopia/mypage/controller/MyPageController.java
  src/main/java/com/sh/pettopia/mypage/dto/ProfileUpdateRequestDto.java
  src/main/java/com/sh/pettopia/mypage/repository/MyPageRepository.java
  src/main/java/com/sh/pettopia/mypage/service/MyPageService.java
  src/main/resources/static/css/enterprise/detail.css
  src/main/resources/static/images/enterprise/noReview.png
  src/main/resources/static/js/enterprise/detail.js
  src/main/resources/templates/enterprise/detail.html
  src/main/resources/templates/enterprise/location.html
  src/main/resources/templates/index.html
Labels: 업체

#193 Feat: 본인이 작성한 업체의 리뷰를 삭제 가능 #87 Feat: OCR로 읽어온 영수증 정보 DB저장 #188
  sql/tbl_ent_review.sql
  sql/tbl_enterprise.sql
  sql/tbl_member.sql
  sql/tbl_petsitter.sql
  src/main/java/com/sh/pettopia/enterprise/controller/EnterpriseController.java
  src/main/java/com/sh/pettopia/enterprise/controller/HospitalController.java
  src/main/java/com/sh/pettopia/enterprise/controller/PharmacyController.java
  src/main/java/com/sh/pettopia/enterprise/controller/SalonController.java
  src/main/java/com/sh/pettopia/enterprise/dto/ReviewRegistDto.java
  src/main/java/com/sh/pettopia/enterprise/dto/ReviewResponseDto.java
  src/main/java/com/sh/pettopia/enterprise/entity/Receipt.java
  src/main/java/com/sh/pettopia/enterprise/entity/Review.java
  src/main/java/com/sh/pettopia/enterprise/repository/ReviewRepository.java
  src/main/java/com/sh/pettopia/enterprise/service/ReviewService.java
  src/main/java/com/sh/pettopia/naver_clova_ocr_api/ocr/service/OcrService.java
  src/main/resources/static/js/enterprise/detail.js
  src/main/resources/static/json/hospitalData.json
  src/main/resources/templates/enterprise/detail.html
  src/main/resources/templates/enterprise/hospitalreview.html
  src/main/resources/templates/enterprise/location.html
  src/main/resources/templates/enterprise/test.html
Labels: 업체

#208 Design : 메인 페이지 디자인 #205
  src/main/java/com/sh/pettopia/Hojji/config/WebSecurityConfig.java
  src/main/resources/static/css/login/login.css
  src/main/resources/static/css/mainPage/index.css
  src/main/resources/static/css/pesitting/petsittingmain.css
  src/main/resources/static/images/index/3C3DB8C6-47B5-468A-8C0B-C0FC14FD2B60_4_5005_c.jpeg
  src/main/resources/static/images/index/img.png
  src/main/resources/static/js/login/login.js
  src/main/resources/static/js/mainPage/index.js
  src/main/resources/static/prepros-6.config
  src/main/resources/static/svg/badukDog.svg
  src/main/resources/static/svg/brownDog.svg
  src/main/resources/static/svg/community.svg
  src/main/resources/static/svg/community2.svg
  src/main/resources/static/svg/dhdhd.svg
  src/main/resources/static/svg/dogs.svg
  src/main/resources/static/svg/helpDog.svg
  src/main/resources/static/svg/hospital.svg
  src/main/resources/static/svg/map.svg
  src/main/resources/static/svg/petcare.svg
  src/main/resources/static/svg/pharmacy.svg
  src/main/resources/static/svg/receipt.svg
  src/main/resources/static/svg/salon.svg
  src/main/resources/static/svg/whiteDog.svg
  src/main/resources/templates/auth/login.html
  src/main/resources/templates/auth/ㅇㅇㅇ.html
  src/main/resources/templates/community/dfdf.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/index.html
  src/main/resources/templates/layout/default.html
  src/main/resources/templates/petsitter/petsittingmain.html
Labels: enhancement, PageDesign

#211 update 예약 및 결제
  .idea/misc.xml
  src/main/java/com/sh/pettopia/choipetsitter/controller/PetSitterController.java
  src/main/java/com/sh/pettopia/choipetsitter/dto/PetSitterRegisterDto.java
  src/main/java/com/sh/pettopia/kakaopay/service/PayService.java
  src/main/java/com/sh/pettopia/mypage/controller/MyPageController.java
  src/main/resources/templates/mypage/mypage.html
  src/main/resources/templates/petsitter/detail.html
  src/main/resources/templates/petsitter/list.html
  src/main/resources/templates/petsitter/registerprofile.html
  src/main/resources/templates/petsitter/reviewdetail.html
  src/main/resources/templates/petsitter/sittinglist.html
Labels: 일반회원, 펫시터

#228 Feat: [관리자] 시터권한 요청 수락/거절시 status, Role 변경 #24
  build.gradle
  src/main/java/com/sh/pettopia/Hojji/user/User.java
  src/main/java/com/sh/pettopia/Hojji/user/admin/controller/AdminController.java
  src/main/java/com/sh/pettopia/Hojji/user/admin/entity/PetsitterQualificationApplicationEntity.java
  src/main/java/com/sh/pettopia/Hojji/user/member/dto/MemberListResponseDto.java
  src/main/java/com/sh/pettopia/Hojji/user/member/entity/SitterStatus.java
  src/main/java/com/sh/pettopia/Hojji/user/member/repository/MemberRepository.java
  src/main/java/com/sh/pettopia/Hojji/user/member/service/MemberService.java
  src/main/java/com/sh/pettopia/mypage/dto/PesitterQualificationRegistRequestDto.java
  src/main/java/com/sh/pettopia/mypage/service/MyPageService.java
  src/main/resources/application.yml
  src/main/resources/templates/admin/sitterList.html
  src/main/resources/templates/admin/sitterRequestList.html
  src/main/resources/templates/admin/userProfile.html
Labels: 관리자

#233 Feat: [관리자] 시터요청 승인/거절 시 authoritiy,sitterStatus 변경 #24
  src/main/java/com/sh/pettopia/Hojji/user/admin/entity/PetsitterQualificationApplicationEntity.java
  src/main/java/com/sh/pettopia/Hojji/user/admin/repository/AdminRepository.java
  src/main/java/com/sh/pettopia/Hojji/user/admin/service/AdminService.java
  src/main/java/com/sh/pettopia/Hojji/user/member/controller/UserProfileController.java
  src/main/java/com/sh/pettopia/Hojji/user/member/repository/MemberRepository.java
  src/main/java/com/sh/pettopia/Hojji/user/member/service/MemberService.java
  src/main/java/com/sh/pettopia/mypage/dto/PetsitterQulificationResponseDto.java
  src/main/resources/templates/admin/sitterRequestForm.html
  src/main/resources/templates/admin/sitterRequestList.html
  src/main/resources/templates/admin/userProfile2.html
Labels: 관리자, 업체

#234 update 펫시터 자격 신청, 펫시터 등록
  src/main/java/com/sh/pettopia/Hojji/pet/service/PetService.java
  src/main/java/com/sh/pettopia/Hojji/user/admin/controller/AdminController.java
  src/main/java/com/sh/pettopia/Hojji/user/member/repository/MemberRepository.java
  src/main/java/com/sh/pettopia/Hojji/user/member/service/MemberService.java
  src/main/java/com/sh/pettopia/choipetsitter/service/PetSitterService.java
Labels: 관리자

#235 Update: 펫시터신청폼 createdAt컬럼 추가 #66 / design: 프로필, 신청서 링크 경로 수정/ 테이블 디자인 변경 #20 #22
  src/main/java/com/sh/pettopia/Hojji/user/admin/entity/PetsitterQualificationApplicationEntity.java
  src/main/java/com/sh/pettopia/Hojji/user/admin/repository/AdminRepository.java
  src/main/java/com/sh/pettopia/Hojji/user/admin/service/AdminService.java
  src/main/java/com/sh/pettopia/Hojji/user/member/controller/UserProfileController.java
  src/main/java/com/sh/pettopia/Hojji/user/member/dto/PendingSitterMemberDto.java
  src/main/java/com/sh/pettopia/Hojji/user/member/repository/MemberRepository.java
  src/main/java/com/sh/pettopia/Hojji/user/member/service/MemberService.java
  src/main/java/com/sh/pettopia/enterprise/entity/Review.java
  src/main/java/com/sh/pettopia/mypage/dto/PesitterQualificationRegistRequestDto.java
  src/main/java/com/sh/pettopia/mypage/dto/PetsitterQulificationResponseDto.java
  src/main/resources/templates/admin/dashboard.html
  src/main/resources/templates/admin/memberList.html
  src/main/resources/templates/admin/sitterList.html
  src/main/resources/templates/admin/sitterRequestForm.html
  src/main/resources/templates/admin/sitterRequestList.html
  src/main/resources/templates/admin/userProfile.html
  src/main/resources/templates/mypage/petsitterRegist.html
Labels: 관리자

#236 Design : 레이아웃 디자인 수정 #205
  README.md
  src/main/resources/static/css/community/postList.css
  src/main/resources/static/css/enterprise/location.css
  src/main/resources/static/css/pesitting/petsittingmain.css
  src/main/resources/static/css/petsitter/registerpost.css
  src/main/resources/static/css/petsitter/registerprofile.css
  src/main/resources/static/css/petsitter/schedule.css
  src/main/resources/static/svg/brush.png
  src/main/resources/static/svg/calender.png
  src/main/resources/static/svg/cutiDog.svg
  src/main/resources/static/svg/duck.png
  src/main/resources/static/svg/foot.png
  src/main/resources/static/svg/medicine.png
  src/main/resources/static/svg/oldDog.png
  src/main/resources/static/svg/pharmacy.png
  src/main/resources/static/svg/puppy.png
  src/main/resources/static/svg/teddy-bear.svg
  src/main/resources/static/svg/walk.png
  src/main/resources/templates/community/postList.html
  src/main/resources/templates/enterprise/location.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/petsitter/petsittingmain.html
  src/main/resources/templates/petsitter/registerpost.html
  src/main/resources/templates/petsitter/registerprofile.html
  src/main/resources/templates/petsitter/schedule.html
  src/main/resources/templates/petsitter/startjob.html
Labels: PageDesign

#242 Design : 페이지 레이아웃 수정 #205
  src/main/resources/static/css/mainPage/index.css
  src/main/resources/static/css/petsitter-finder/careregistrationlist.css
  src/main/resources/static/css/petsitter/list.css
  src/main/resources/static/js/mainPage/index.js
  src/main/resources/static/svg/angryDog.jpeg
  src/main/resources/static/svg/puppy.jpeg
  src/main/resources/static/svg/sickDog.jpeg
  src/main/resources/templates/index.html
  src/main/resources/templates/petsitter/detail.html
  src/main/resources/templates/petsitter/list.html
  src/main/resources/templates/petsitter/registerpost.html
  src/main/resources/templates/petsitterfinder/careregistrationlist.html
Labels: PageDesign

#244 Design : carereistrationlist.html 수정 #205
  src/main/resources/static/css/petsitter-finder/careregistrationlist.css
  src/main/resources/templates/petsitterfinder/careregistrationlist.html
Labels: PageDesign
